# Generated by Django 5.0.6 on 2025-07-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_userprofile_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reference',
            field=models.CharField(blank=True, help_text='Reference source (e.g., Robbins p.117)', max_length=200),
        ),
    ]
