# Generated by Django 5.0.6 on 2025-07-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='parent',
        ),
        migrations.AddField(
            model_name='tag',
            name='apply_to_all_resources',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='apply_to_mcq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='apply_to_notes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='apply_to_videos',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Subtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='If blank, inherits from parent tag', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtags', to='core.tag')),
            ],
            options={
                'verbose_name': 'Subtag',
                'verbose_name_plural': 'Subtags',
                'ordering': ['name'],
                'unique_together': {('tag', 'name')},
            },
        ),
    ]
